security:
    providers:
        usuarios:
            entity: {class : LaTorres\UsuarioBundle\Entity\Usuario,property: username}

    firewalls:
        frontend:
            pattern: ^/*
            anonymous: ~
            form_login:
                login_path: usuario_login
                check_path: usuario_login_check
                default_target_path: /
                always_use_default_target_path: true
            logout:
                path: usuario_logout
                target: /
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/registro, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/*, roles: ROLE_USUARIO }
        

    encoders:
        LaTorres\UsuarioBundle\Entity\Usuario: plaintext