parameters:
#    bodega.example.class: LaTorres\BodegaBundle\Example

services:
#    bodega.example:
#        class: %bodega.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
