parameters:
#    reportes.example.class: LaTorres\ReportesBundle\Example

services:
#    reportes.example:
#        class: %reportes.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
