usuario_login:
    pattern: /login
    defaults: { _controller:UsuarioBundle:Default:login }
usuario_login_check:
    pattern: /login_check
usuario_logout:
    pattern: /logout
buscar_usuario:
    pattern: /buscar-usuario
    defaults: { _controller:UsuarioBundle:Default:buscarEmpleado }
